[lint]
select = ["E", "F", "W", "B", "I"]
ignore = ["E501"]

[lint.per-file-ignores]
"**/__init__.py" = ["F401"]
"**/__manifest__.py" = ["B018"]

[format]
docstring-code-format = false
skip-magic-trailing-comma = false