{
    'name': 'HR Hospital',
    'version': '17.0.1.0.0',
    'depends': ['base', 'web'],
    'author': 'Paul',
    'category': 'Human Resources',
    'installable': True,
    'application': True,
    'website': 'https://www.odoo.com',
    'license': 'OPL-1',
    'data': [
        'security/ir.model.access.csv',
        'report/report_doctor.xml',
        'report/report_doctor_template.xml',

        'views/diagnosis_views.xml',
        'views/hr_hospital_menu.xml',
        'views/specialty_views.xml',
        'views/visit_views.xml',
        'views/doctor_views.xml',
        'views/patient_views.xml',
        'views/disease_views.xml',

        'wizards/patient_doctor_update_wizard_view.xml',
        'wizards/diagnosis_report_wizard_view.xml',
    ],
    'demo': [
        'demo/demo_specialty_data.xml',
        'demo/demo_doctor_data.xml',
        'demo/demo_patient_data.xml',
        'demo/demo_disease_data.xml',
        'demo/demo_visit_data.xml',
        'demo/demo_diagnosis_data.xml',
    ],
}